name: Artifact Demo

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create report
        run: |
          mkdir results
          echo "Tests Passed" > results/report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: results/
