name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying..."
          sleep 20
          echo "Deployment finished"
